theme = "hallo"
baseURL = "https://kjappelbaum.github.io"
languageCode = "en-us"
title = "Kevin Maik Jablonka"
publishdir="docs"

[Author]
    name = "Kevin"

[params]
    greeting = "Hi." 
    [params.colors]
        background = "#1F4477"
        foreground = "#E0BB88"
        hover = "#E8F1F2"
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/kjappelbaum"
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/kmjablonka"
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/kevin-maik-jablonka-538655200/"
    [[params.links]]
        iconorigin = "ai"
        iconset = "ai"
        icon = "google-scholar"
        title = "Google Scholar"
        url = "https://scholar.google.com/citations?user=R2ntI8IAAAAJ&hl=en"
    [[params.links]]
        iconorigin = "ai"
        iconset = "ai"
        icon = "orcid"
        title = "ORCID"
        url = "https://orcid.org/0000-0003-4894-4660n"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "email"
        url = "https://mailhide.io/e/o4LeOUlq"
    [[params.links]]
        icon = "cv"
        iconset = "ai"
        iconorigin = "ai"
        title = "CV"
        url = "https://www.dropbox.com/s/8om2gjyc7ab5v9d/cv.pdf?dl=0"
    [[params.links]]
        icon = "calendar"
        iconset = "fas"
        title = "Talk to me"
        url = "https://calendly.com/kjappelbaum"

